// Populate year and day dropdowns on page load
window.onload = function() {
    // Populate year dropdown
    const yearSelect = document.getElementById("year");
    const currentYear = new Date().getFullYear();
    
    // Add the current year first
    const currentYearOption = document.createElement("option");
    currentYearOption.value = currentYear;
    currentYearOption.textContent = currentYear;
    yearSelect.appendChild(currentYearOption);

    // Add previous years in descending order
    for (let i = currentYear - 1; i >= 1950; i--) {
        const option = document.createElement("option");
        option.value = i;
        option.textContent = i;
        yearSelect.appendChild(option);
    }

    // Populate day dropdown
    const daySelect = document.getElementById("day");
    for (let i = 1; i <= 31; i++) {
        const option = document.createElement("option");
        option.value = String(i).padStart(2, '0'); // Ensure two digits
        option.textContent = i;
        daySelect.appendChild(option);
    }
};

document.getElementById("bootlegForm").addEventListener("submit", function(event) {
    event.preventDefault(); // Prevent form submission

    // Get values from the form
    const artist = document.getElementById("artist").value;
    const year = document.getElementById("year").value;
    const month = document.getElementById("month").value.padStart(2, '0'); // Ensure two digits for month
    const day = document.getElementById("day").value.padStart(2, '0'); // Ensure two digits for day
    const date = `${year}-${month}-${day}`; // Combine year, month, and day
    const venue = document.getElementById("venue").value; // Get venue input
    const city = document.getElementById("city").value;
    const state = document.getElementById("state").value; // Can be empty if not a US show
    const country = document.getElementById("country").value;
    const tour = document.getElementById("tour").value; // Get tour input
    const mics = document.getElementById("mics").value;
    const power = document.getElementById("power").value;
    const recorder = document.getElementById("recorder").value;
    const media = document.getElementById("media").value;
    const device = document.getElementById("device").value;
    const initialFormat = document.getElementById("initialFormat").value;
    const processingSoftware = document.getElementById("processingSoftware").value;
    const trackSoftware = document.getElementById("trackSoftware").value;
    const conversionSoftware = document.getElementById("conversionSoftware").value;
    const finalFormat = document.getElementById("finalFormat").value;
    const recordedBy = document.getElementById("recordedBy").value;
    const tracklistInput = document.getElementById("tracklist").value;

    // Split tracklist by commas and trim spaces
    const tracklist = tracklistInput.split(',').map(track => track.trim());

  // Generate info content
let info = `${artist}\n${date}\n${venue}\n${city}${state ? ', ' + state : ''}, ${country}\n\n`; 


    // Add tour
    info += `Tour: ${tour}\n\n`; // Added line break

    // Add source in blockchain format
    info += `Source: ${mics} > ${power} > ${recorder}\n\n`;

    // Add transfer process to the info
    info += `Transfer: ${media} > ${device} > ${initialFormat} > ${processingSoftware} > ${trackSoftware} > ${conversionSoftware} > ${finalFormat}\n\n`;

    info += `Recorded and transferred by ${recordedBy}.\n\n`;

    // Add tracklist heading
    info += `Tracklist:\n`;
    // Add tracklist items
    tracklist.forEach((track, index) => {
        info += `${String(index + 1).padStart(2, '0')} ${track}\n`;
    });

    // Get the current date for the footer
    const compilationDate = new Date().toLocaleDateString(); // Format: MM/DD/YYYY
    // Add generated by message with compilation date
    info += `\nTXT File compiled on ${compilationDate}.\n`;

    // Create a Blob for the text file
    const blob = new Blob([info], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    // Set up the download link
    const downloadLink = document.getElementById("fileDownload");
    const fileName = `${artist} [${date}] ${venue}, ${city}${state ? ', ' + state : ''}, ${country} (${finalFormat}).txt`;
    downloadLink.href = url;
    downloadLink.download = fileName;

    // Display the download link
    downloadLink.style.display = 'block';
});
